# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dzWeather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dzWeather
  pod 'NVActivityIndicatorView'
  pod 'Alamofire', '~> 5.4'
  pod 'AlamofireNetworkActivityLogger', '~> 3.4'
  pod 'RealmSwift', '~>10'
  pod 'GoogleMaps', '5.2.0'
end

